name: 'CD'

on:
  release:
    types: [created]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: oven-sh/setup-bun@v1
        name: Setup bun
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun run test

      - name: Typecheck
        run: bun run typecheck

  publish:
    name: Publish
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
