name: 'CI'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: oven-sh/setup-bun@v1
        name: Setup bun
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check Code Standards
        run: |
          bun run check:code-style
          bun run check:code-formatting

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build
